apiVersion: v1
kind: Service
metadata:
  name: chattingo-backend-service
spec:
  type: LoadBalancer
  selector:
    app: chattingo-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
