apiVersion: apps/v1
kind: Deployment
metadata:
  name: chattingo-backend-deployment
  labels:
    app: chattingo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chattingo-backend
  template:
    metadata:
      labels:
        app: chattingo-backend
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for DB..."
              # Try 30 times (max ~60 seconds)
              for i in $(seq 1 30); do
                nc -z db 3306 && exit 0
                echo "DB not ready, retrying ($i/30)..."
                sleep 2
              done
              echo "DB did not start in time, exiting initContainer."
              exit 1
          imagePullPolicy: Always
      containers:
        - name: chattingo-backend
          image:   routparesh/chattingo-backend:fbea059fdba410d808ddcf947506c7cc26d9f1af
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://db:3306/chattingo_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: test@123
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
      restartPolicy: Always
