name: CI Pipeline

on:
  push:
    branches: [main, docker]

env:
  FRONTEND_IMAGE: routparesh/chattingo-frontend
  BACKEND_IMAGE: routparesh/chattingo-backend

jobs:
  build-test-scan-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test@123
          MYSQL_DATABASE: chattingo_db
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: test@123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------- FRONTEND (Node.js) ----------------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: |
          if [ -f package.json ] && grep -q "\"test\":" package.json; then
            npm test -- --watchAll=false
          else
            echo "⚠️ No test script found in frontend/package.json"
          fi

      # ---------------- BACKEND (Java) ----------------
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Load backend environment variables
        working-directory: ./backend
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/chattingo_db" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=root" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=test@123" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..15}; do
          nc -zv 127.0.0.1 3306 && echo "MySQL is up!" && break
          echo "Waiting for MySQL..."
          sleep 5
          done
      - name: Build backend
        working-directory: ./backend
        run: mvn clean package -DskipTests=false

      - name: Run backend tests
        working-directory: ./backend
        run: mvn test

      # ---------------- SECURITY: GitLeaks ----------------
      - name: Run GitLeaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          args: detect --source . --no-banner --verbose

      # ---------------- QUALITY: SonarQube ----------------
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        with:
          projectBaseDir: ./backend
          args: >
            -Dsonar.projectName=chattingo-backend
            -Dsonar.projectKey=chattingo-backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        with:
          projectBaseDir: ./frontend
          args: >
            -Dsonar.projectName=chattingo-frontend
            -Dsonar.projectKey=chattingo-frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # ---------------- SECURITY: Trivy Scan ----------------
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: .
          format: 'table'
          exit-code: '0'

      # ---------------- DOCKER BUILD & PUSH ----------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend image
        working-directory: ./frontend
        run: |
          docker build -t ${{ env.FRONTEND_IMAGE }}:${{ github.sha }} .
          docker push ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

      - name: Build and Push Backend image
        working-directory: ./backend
        run: |
          docker build -t ${{ env.BACKEND_IMAGE }}:${{ github.sha }} .
          docker push ${{ env.BACKEND_IMAGE }}:${{ github.sha }}

      # ---------------- UPDATE K8S DEPLOYMENT ----------------
      - name: Update image tags in Kubernetes manifests
        run: |
          sed -i "s|routparesh/chattingo-frontend:.*|routparesh/chattingo-frontend:${{ github.sha }}|g" k8s/deployment.yaml

      - name: Commit updated image tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "update images to ${{ github.sha }}"
          git push
